### ISSUE TITLE
Subsystem components

### ISSUE THREAD

**Issue by camearle20** [team401/2018-Robot-Code#16]
We need to add components to the subsystems.  While this is subject to change, it will give us a good representation of where we're headed

**Comment by PChild** [comment]
Reference https://github.com/CrossTheRoadElec/Phoenix-Documentation/blob/master/Migration%20Guide.md for limit switch behavior.

**Comment by PChild** [comment]
Elevator hold carriage should be on a different solenoid than the elevator gear selector. After climbing we would be in elevator low gear AND in elevator hold.

**Comment by PChild** [comment]
Logic to prevent carriage movement until the elevator is deployed may be a good idea. rejectIf(state != DEPLOYED) or something?

Shou we add an error state to the elevator machine? And do we want a sensor on the carriage to verify deploy?

**Comment by PChild** [comment]
Will Signals be used more in the code base? Why use a signal?

**Comment by PChild** [comment]
Please add test mode functionality for all subsystems. This can be a new issue if you want.

**Comment by PChild** [comment]
Differentiate current limits. configContinuousCurrentLimit is available in Phoenix. Refer to migration guide.

**Comment by camearle20** [comment]
Signals are used for the elevator to provide an easy way to externally set its position.  This will make it easier to tell the elevator to go to positions, as we don't have to create a state for each one.  We may use signals for other systems like the intake.
