### ISSUE TITLE
Shutdown coprocessor when match ends

### ISSUE THREAD

**Issue by PChild** [team401/2018-Robot-Code#3]
The vision coprocessor should automatically stop streaming / recording and shutdown when an fms connected match ends.

Should video recording also be tied to a network tables flag so that we can opt to record or not when practicing?

**Comment by camearle20** [comment]
Why do we need to shut down the coprocessor?  It should be fine without shutting down?

**Comment by PChild** [comment]
Avoiding file system corruption? Shutting down is less of an issue than stopping the recording.

**Comment by PChild** [comment]
See related thread from CD: https://www.chiefdelphi.com/forums/showthread.php?p=1541220

I think we either need to go read only for part of the file system with videos saved onto a different partition, or else we should have graceful shutdown plans.

**Comment by camearle20** [comment]
I would save videos onto an external device, such as a thumb drive.  I definitely agree that we need to shut down the recording before power is lost, but I'm not sure there's really a need to gracefully shutdown the Jetson.

**Comment by camearle20** [comment]
Now that the controller is in place, we should be able to do this fairly easily

**Comment by PChild** [comment]
Logic for halting recording needs to be modified to correctly handle transition from auto to teleop. Reopening.
