### ISSUE TITLE
Alternative Motion Controls

### ISSUE THREAD

**Issue by camearle20** [team401/2018-Robot-Code#47]
As build season is coming to an end, it has become increasingly obvious that we need some alternative drivetrain motion controls.  We need to face the fact that our drivetrain might not go straight with motion profiles, and therefore we should be ready with alternatives such as heading-corrected motion profiles and adaptive pure pursuit controllers.  I am making this our highest priority.  This branch will become the active development branch until these alternatives are complete.

**Comment by PChild** [comment]
Can we move the RioProfileRunner out of setup and into a file in the auto directory?

**Comment by PChild** [comment]
We also may want / need a delay step at the beginning of the auto sequences to allow other bots to move first.

**Comment by PChild** [comment]
There also needs to be calls to the elevator gripper machine in the sequences. Otherwise you're going to have a **_BAD TIME_** :-)

**Comment by PChild** [comment]
If I remember correctly the SRX motion profiling had an option to allow you to continue to use the last point as your PIDF setpoint even after the profile had run. Would something like that make sense in our case?

IE until the next move command is invoked we want to let the system continue to run and actively hold position / header.

**Comment by PChild** [comment]
How slow is loading the CSV files in? Would it be worthwhile to have files preloaded into memory?

**Comment by PChild** [comment]
Why are we waiting for the elevator to deploy in the assembled auto sequences? Can we drive while it's deploying? Don't we _**HAVE**_ to drive while it's deploying since it will hit the driver station wall if we deploy without moving?

**Comment by PChild** [comment]
Can we remove RioProfileRunnerOld?

**Comment by PChild** [comment]
Reopening to allow comments to be addressed. This branch got merged into master before these were addressed.

**Comment by camearle20** [comment]
1. RioProfileRunner is in auto, it was used in Setup for testing purposes.
2. The delay is already a feature of the auto framework, specifiable by a smartdashboard key.
3. Unrelated to this issue
4. Not using SRX motion profiling anymore
5. The loading time is negligible, and loading all files into memory would quickly run us out of memory.
6. Unrelated to this issue
7. RioProfileRunnerOld was already deleted, MotionProfileRunner is being kept for possible future use.
