### ISSUE TITLE
Auto sequencing and elevator deploy

### ISSUE THREAD

**Issue by PChild** [team401/2018-Robot-Code#56]
Why are we waiting for the elevator to deploy in the assembled auto sequences? Can we drive while it's deploying? Don't we HAVE to drive while it's deploying since it will hit the driver station wall if we deploy without moving?

**Comment by camearle20** [comment]
We aren't really waiting for the elevator to deploy, we are just waiting for it to start.  After this, the drivetrain will kick on as quickly as possible.  Closing for now, we might need to revisit this in the future.
