### ISSUE TITLE
Please add anti-tipping code

### ISSUE THREAD

**Issue by PChild** [team401/2018-Robot-Code#84]
"It will take like five seconds."

**Comment by rkap51** [comment]
> because i am number one athletic performance
<sub>[View in Slack](https://team-401.slack.com/archives/C0Q571B3L/p1535082590000100)</sub>

**Comment by rkap51** [comment]
> implying that i do a lot of running
<sub>[View in Slack](https://team-401.slack.com/archives/C0Q571B3L/p1535082582000100)</sub>

**Comment by rkap51** [comment]
> wow camerun
<sub>[View in Slack](https://team-401.slack.com/archives/C0Q571B3L/p1535082578000100)</sub>

**Comment by rkap51** [comment]
> LET'S READ THE RULES
<sub>[View in Slack](https://team-401.slack.com/archives/C0Q571B3L/p1535082499000100)</sub>

**Comment by rkap51** [comment]
> there IS another wil payne site
<sub>[View in Slack](https://team-401.slack.com/archives/C0Q571B3L/p1535082742000200)</sub>

**Comment by rkap51** [comment]
> hey ryan
<sub>[View in Slack](https://team-401.slack.com/archives/C0Q571B3L/p1535082761000100)</sub>

**Comment by rkap51** [comment]
> The big bad code police
<sub>[View in Slack](https://team-401.slack.com/archives/C0Q571B3L/p1535082875000200)</sub>

**Comment by rkap51** [comment]
> how does it feel to be the son of linus torvalds
<sub>[View in Slack](https://team-401.slack.com/archives/C0Q571B3L/p1535082978000100)</sub>

**Comment by rkap51** [comment]
> MY DAD OWNS GIT
<sub>[View in Slack](https://team-401.slack.com/archives/C0Q571B3L/p1535082960000100)</sub>

**Comment by PChild** [comment]
Robot is getting disassembled soon. closing out issue.
